

const HomePage = () => {
    return (
        <div>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
            <h2>Home page</h2>
        </div>
    );
};

export default HomePage;